apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    alertmanagerMain:
      nodeSelector:
        role: monitoring-node
      volumeClaimTemplate:
        metadata:
          name: alertmanager
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 40Gi
    prometheusK8s:
      nodeSelector:
        role: monitoring-node
      volumeClaimTemplate:
        metadata:
          name: prometheusdb
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 40Gi
    prometheusOperator:
      nodeSelector:
        role: monitoring-node
    grafana:
      nodeSelector:
        role: monitoring-node
    k8sPrometheusAdapter:
      nodeSelector:
        role: monitoring-node
    kubeStateMetrics:
      nodeSelector:
        role: monitoring-node
    telemeterClient:
      nodeSelector:
        role: monitoring-node
    openshiftStateMetrics:
      nodeSelector:
        role: monitoring-node
